repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.4
    hooks:
      - id: ruff
        name: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy src/revhash --ignore-missing-imports
        language: system
        types: [python]
        files: ^src/revhash/
        pass_filenames: false
